### PR TITLE
Switch to LALRPOP

### PR DESCRIPTION
**Pull request by ghost**
Peg depends on libsyntax shipped with the compiler, and thus breaks quite regularly.

This PR changes the parser to LALRPOP, which looks more stable.

### CODE REVIEW

**Comment by ghost** [comment]
Closes #4

**Comment by lthms** [comment]
I will have a look today. Is there any tests I might perform?

**Comment by ghost** [comment]
You can run `cargo run --example repl`, play a bit with it and check the output. The grammar should give an idea of what is currently supported.

Note: parsing of floats is not supported yet.

**Comment by ghost** [comment]
Oops I just realized the lexer doesn't accept '.' in variable names (which is used in Lycan), let me fix this.

**Comment by ghost** [comment]
OK it should be fixed now, Lycan can now run with this version of Aariba (I will however finish the current management API work before using this latest version)

**Comment by lthms** [comment]
LGTM

**Pull request merged**
